//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaliacaoRenan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suplemento
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Forma { get; set; }
        public string Origem { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Marca Marca { get; set; }
    }
}
